import { LeadCaptureData } from '@/lib/types'

function formatCurrency(amount: number) {
  return amount.toLocaleString('en-AU', {
    style: 'currency',
    currency: 'AUD',
    minimumFractionDigits: 2,
  })
}

export function buildQuoteEmailHtml(lead: LeadCaptureData) {
  const total = lead.quoteData.total || 0

  return `
<!doctype html>
<html>
  <body style="margin:0;padding:0;background:#f4f4f5;font-family:Arial,Helvetica,sans-serif;">
    <table width="100%" cellpadding="0" cellspacing="0" style="background:#f4f4f5;padding:24px 12px;">
      <tr><td align="center">
        <table width="620" cellpadding="0" cellspacing="0" style="max-width:620px;width:100%;background:#fff;border-radius:12px;overflow:hidden;">
          <tr>
            <td style="background:#1f2937;color:#fff;padding:24px;">
              <h1 style="margin:0;font-size:22px;">Your QBCC Insurance Quote</h1>
              <p style="margin:10px 0 0;opacity:.9;">Thanks for using the QBCC calculator. Here are your results:</p>
            </td>
          </tr>
          <tr>
            <td style="padding:24px;">
              <div style="border:1px solid #e4e4e7;border-radius:10px;padding:18px;background:#fafafa;margin-bottom:18px;">
                <p style="margin:0;color:#71717a;font-size:13px;">ESTIMATED TOTAL</p>
                <p style="margin:8px 0 0;font-size:34px;line-height:1.1;color:#18181b;font-weight:700;">${formatCurrency(total)}</p>
              </div>
              <table width="100%" cellpadding="0" cellspacing="0" style="border-collapse:collapse;">
                <tr><td style="padding:10px 0;border-bottom:1px solid #f1f5f9;color:#52525b;">Work Type</td><td style="padding:10px 0;border-bottom:1px solid #f1f5f9;color:#18181b;text-align:right;font-weight:600;">${lead.quoteData.workType || 'Not provided'}</td></tr>
                <tr><td style="padding:10px 0;border-bottom:1px solid #f1f5f9;color:#52525b;">Insurable Value</td><td style="padding:10px 0;border-bottom:1px solid #f1f5f9;color:#18181b;text-align:right;font-weight:600;">${formatCurrency(lead.quoteData.insurableValue || 0)}</td></tr>
                <tr><td style="padding:10px 0;border-bottom:1px solid #f1f5f9;color:#52525b;">Units</td><td style="padding:10px 0;border-bottom:1px solid #f1f5f9;color:#18181b;text-align:right;font-weight:600;">${lead.quoteData.units || 1}</td></tr>
                <tr><td style="padding:10px 0;border-bottom:1px solid #f1f5f9;color:#52525b;">QBCC Premium</td><td style="padding:10px 0;border-bottom:1px solid #f1f5f9;color:#18181b;text-align:right;font-weight:600;">${formatCurrency(lead.quoteData.premium || 0)}</td></tr>
                <tr><td style="padding:10px 0;color:#52525b;">QLeave Levy</td><td style="padding:10px 0;color:#18181b;text-align:right;font-weight:600;">${formatCurrency(lead.quoteData.qleave || 0)}</td></tr>
              </table>
              <p style="margin:20px 0 0;color:#71717a;font-size:13px;">This is an estimate generated by the QBCC Insurance Calculator and should be used as a guide.</p>
            </td>
          </tr>
        </table>
      </td></tr>
    </table>
  </body>
</html>`
}
